// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOroNLhd7FQO_kZgVRj7Brlzdw0cvs-II',
    appId: '1:731952992687:web:2a9276779a89c541dd1f5a',
    messagingSenderId: '731952992687',
    projectId: 'harvestsync-6443d',
    authDomain: 'harvestsync-6443d.firebaseapp.com',
    storageBucket: 'harvestsync-6443d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChAFDv0AuGT8_9Fo_m-Md9N6cBqRuq0Ls',
    appId: '1:731952992687:android:e2d155c3b626876ddd1f5a',
    messagingSenderId: '731952992687',
    projectId: 'harvestsync-6443d',
    storageBucket: 'harvestsync-6443d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3km3V0XoaDAE5cIoqbpScBOCPTtx3VW4',
    appId: '1:731952992687:ios:f13721708d84c999dd1f5a',
    messagingSenderId: '731952992687',
    projectId: 'harvestsync-6443d',
    storageBucket: 'harvestsync-6443d.firebasestorage.app',
    iosBundleId: 'com.example.eeppApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3km3V0XoaDAE5cIoqbpScBOCPTtx3VW4',
    appId: '1:731952992687:ios:f13721708d84c999dd1f5a',
    messagingSenderId: '731952992687',
    projectId: 'harvestsync-6443d',
    storageBucket: 'harvestsync-6443d.firebasestorage.app',
    iosBundleId: 'com.example.eeppApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOroNLhd7FQO_kZgVRj7Brlzdw0cvs-II',
    appId: '1:731952992687:web:6d0386702ded32d0dd1f5a',
    messagingSenderId: '731952992687',
    projectId: 'harvestsync-6443d',
    authDomain: 'harvestsync-6443d.firebaseapp.com',
    storageBucket: 'harvestsync-6443d.firebasestorage.app',
  );
}
